#######################################
#        Makefile for GRYFX
#######################################
#
# To build GRYFX, use the build_gryfx
# script which is included with this
# distribution. It automatically loads
# the required modules for a given
# system and checks you have set the
# right environment variables
#
#######################################

TARGET    = gryfx

#######################################
# Include system-dependent make variables
#######################################

ifndef GK_SYSTEM
	ifdef SYSTEM
$(warning SYSTEM environment variable is obsolete)
$(warning use GK_SYSTEM instead)
	GK_SYSTEM = $(SYSTEM)
	else
$(error GK_SYSTEM is not set)
	endif
endif
include Makefile.$(GK_SYSTEM)

include Makefile.depend

############################
## Setup Compiler Flags
###########################

#CC = g++
LD = $(NVCC)
GEO_LIBS=${GS2}/geometry_c_interface.o  # ${GS2}/utils.a #${GS2}/geo.a
GS2_CUDA_FLAGS=-I ${GS2} ${GS2}/libgs2.a ${GS2}/libsimpledataio.a 

CFLAGS= ${CUDA_INC} ${MPI_INC} #${FFT_INC} ${NETCDF_INC} -I $(PWD)/include -I$(PWD) -I$(GS2)/diagnostics/simpledataio/include --compiler-options '-fPIC'
LDFLAGS=$(CUDA_LIB) ${MPI_LIB} #${GEO_LIBS} ${FFT_LIB} ${NETCDF_LIB} ${FORTRAN_LIBS} ${GS2_CUDA_FLAGS}

VPATH=.:src:..

ifeq ($(GS2_zonal),on)
  NVCCFLAGS += -D GS2_zonal 
endif
ifeq ($(PROFILE),on)
  NVCCFLAGS += -D PROFILE 
endif

ifeq ($(GS2_all),on)
  NVCCFLAGS += -D GS2_all -I ${GS2}
  GS2_CUDA_FLAGS=${GS2}/libgs2.a
endif

#to turn off warnings...
#NVCCFLAGS += -w

#TARGET = gryfx

##########################
## Suffix Build Rules
#############################

.SUFFIXES:
.SUFFIXES: .c .cpp .cu .o
.DEFAULT_GOAL := $(TARGET)

HEADERS=$(wildcard include/*.h) 

.cu.o: $(HEADERS)
	$(NVCC) -c $(CFLAGS) $(NVCCFLAGS) $< 

obj/%.o: %.cu $(HEADERS)
	$(NVCC) -c -o $@ $< $(CFLAGS) $(NVCCFLAGS) -I. -I include

obj/%.o: %.cpp $(HEADERS)
	$(CC) -c -o $@ $< $(CFLAGS) -I. -I include

#####################################
# Rule for building the system_config
# used by the build script
#####################################

ifdef STANDARD_SYSTEM_CONFIGURATION
system_config: Makefiles/Makefile.$(GK_SYSTEM) Makefile
	@echo "#!/bin/bash " > system_config
	@echo "$(STANDARD_SYSTEM_CONFIGURATION)" >> system_config
	@sed -i 's/^ //' system_config

else
.PHONY: system_config
system_config:
	$(error "STANDARD_SYSTEM_CONFIGURATION is not defined for this system")
endif

#######################################
# Rules for building gryfx
####################################


libgryfx.a: everything_else.o $(MODULES)
	ar cr $@ $^
	ranlib $@

everything_else.o: $(CU_DEPS) $(GS2)/geo/geometry_c_interface.h $(HEADERS)


# main program
$(TARGET): obj/main.o obj/gryfx_lib.o obj/inputs.o obj/geometry.o #libgryfx.a $(GS2)/libgs2.a 
	$(NVCC)  -o $@  $^ $(CFLAGS) $(NVCCFLAGS) $(LDFLAGS) 



$(MODULES): $(HEADERS)

namelist_defaults.c: namelist_defaults.in
	echo "/* Do not edit this file!! It is created automatically from namelist_defaults.in */" > namelist_defaults.c
	echo "char  default_namelist_string[] = \"\\\\n\\" >> namelist_defaults.c
	cat namelist_defaults.in | sed -e 's/$$/\\n\\/' | sed -e 's/"/\\"/g' >> namelist_defaults.c
	echo "\";" >> namelist_defaults.c

#######################################
# Rules for building gryfx dumb
# used for testing Trinity interface
####################################
    
gryfx_lib_dumb.o: gryfx_lib.h

gryfx_lib_dumb.a: gryfx_lib_dumb.o
	ar cr $@ $<
	ranlib $@

gryfx_dumb: gryfx.o gryfx_lib_dumb.a
	$(NVCC)  -o $@ $(NVCCFLAGS) $(CUDA_LIBS) $< gryfx_lib_dumb.a ${GEO_LIBS} ${FORTRAN_LIBS} 


gryfx_hybrid.o: 
	$(NVCC) -c $(NVCCFLAGS) -D GS2_zonal -I ${GS2} $(CUDA_INC) $< main.cu


########################
# Cleaning up
########################


clean: 
	rm -rf namelist_defaults.cu *.o obj/*.o *~ \#*

distclean: clean clean_tests
	rm -rf $(TARGET)



#########################
# Misc
#######################


test_make:
	@echo TARGET=    $(TARGET)
	@echo SDKDIR=    $(SDKDIR)
	@echo NVCC=      $(NVCC)
	@echo NVCCFLAGS= $(NVCCFLAGS)
	@echo CUDA_INC=  $(CUDA_INC)
	@echo CUDA_LIBS=  $(CUDA_LIBS)



