#######################################
#        Makefile for GRYFX
#######################################
#
# To build GRYFX, use the build_gryfx
# script which is included with this
# distribution. It automatically loads
# the required modules for a given
# system and checks you have set the
# right environment variables
#
#######################################

TARGET    = gryfx++

#######################################
# Include system-dependent make variables
#######################################

ifndef GK_SYSTEM
	ifdef SYSTEM
$(warning SYSTEM environment variable is obsolete)
$(warning use GK_SYSTEM instead)
	GK_SYSTEM = $(SYSTEM)
	else
$(error GK_SYSTEM is not set)
	endif
endif
include Makefile.$(GK_SYSTEM)

############################
## Setup Compiler Flags
###########################

CC = $(NVCC)
LD = $(NVCC)
GEO_LIBS=${GS2}/geometry_c_interface.o 
GS2_CUDA_FLAGS=-I ${GS2} ${GS2}/libgs2.a ${GS2}/libsimpledataio.a 

CFLAGS= ${CUDA_INC} ${MPI_INC} 
LDFLAGS=$(CUDA_LIB) ${MPI_LIB} 

DEBUG_FLAGS = -g -G
#CFLAGS += ${DEBUG_FLAGS}

#####################################
# Rule for building the system_config
# used by the build script
#####################################

ifdef STANDARD_SYSTEM_CONFIGURATION
system_config: Makefiles/Makefile.$(GK_SYSTEM) Makefile
	@echo "#!/bin/bash " > system_config
	@echo "$(STANDARD_SYSTEM_CONFIGURATION)" >> system_config
	@sed -i 's/^ //' system_config

else
.PHONY: system_config
system_config:
	$(error "STANDARD_SYSTEM_CONFIGURATION is not defined for this system")
endif

VPATH=.:src

##########################
## Suffix Build Rules
#############################

.SUFFIXES:
.SUFFIXES: .c .cpp .cu .o
.DEFAULT_GOAL := $(TARGET)

HEADERS=$(wildcard include/*.h) 

## special dependencies
obj/parameters.o: inputs/namelist_defaults.c c_fortran_namelist3.c
obj/solver.o: qneut_kernel.cu 

obj/%.o: %.cu $(HEADERS)
	$(NVCC) -dc -o $@ $< $(CFLAGS) $(NVCCFLAGS) -I. -I include

obj/%.o: %.cpp $(HEADERS)
	$(CC) -c -o $@ $< $(CFLAGS) -I. -I include

inputs/namelist_defaults.c: inputs/namelist_defaults.in
	echo "/* Do not edit this file!! It is created automatically from namelist_defaults.in */" > $@
	echo "char  default_namelist_string[] = \"\\\\n\\" >> $@
	cat $< | sed -e 's/$$/\\n\\/' | sed -e 's/"/\\"/g' >> $@
	echo "\";" >> $@


#######################################
# Rules for building gryfx
####################################

OBJS = main.o run_gryfx.o gryfx_lib.o parameters.o geometry.o grids.o moments.o fields.o solver.o linear.o timestepper.o diagnostics.o device_funcs.o grad_parallel.o closures.o

# main program
$(TARGET): $(addprefix obj/, $(OBJS))
	$(NVCC) -o $@  $^ $(CFLAGS) $(NVCCFLAGS) $(LDFLAGS) 


########################
# Cleaning up
########################


clean: 
	rm -rf src/namelist_defaults.c *.o obj/*.o *~ \#*

distclean: clean clean_tests
	rm -rf $(TARGET)



#########################
# Misc
#######################


test_make:
	@echo TARGET=    $(TARGET)
	@echo SDKDIR=    $(SDKDIR)
	@echo NVCC=      $(NVCC)
	@echo NVCCFLAGS= $(NVCCFLAGS)
	@echo CUDA_INC=  $(CUDA_INC)
	@echo CUDA_LIBS=  $(CUDA_LIBS)



