EXECUTABLE := zfft

CUFILES := main.cu

CU_DEPS := \
       zfft_kernel.cu \
       zderiv.cu \
       zhilbert.cu \
       zderivtest.cu \
       zhilberttest.cu \
       
USECUFFT := 1

include ../../../common/common.mk
       
