/* Do not edit this file!! It is created automatically from namelist_defaults.in */
char  default_namelist_string[] = "\n\
&gx\n\
 debug = \"off\"\n\
\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 !! Spatial domain   !!\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 ntheta = 32\n\
 nperiod = 1\n\
 nx = 16 \n\
 ny = 16\n\
 y0 = 10\n\
 x0 = 10\n\
 boundary_option=\"linked\"\n\
\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 !! v-resolution     !!\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 nhermite  = 4\n\
 nlaguerre = 2\n\
\n\
 closure_model = 'smith_perp'\n\
 closure_model = 'smith_par'\n\
 closure_model = 'beer4+2'\n\
 closure_model = 'none'\n\
 smith_par_q   = 3\n\
 smith_perp_q  = 3\n\
\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 !! Time domain      !!\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 nstep  = 10000\n\
 nwrite = 1000\n\
 delt   = 0.05\n\
 navg   = 10\n\
 nsave  = 1000\n\
 scheme = rk2\n\
 scheme = rk4\n\
 scheme = k10\n\
\n\
 restart = \"off\"\n\
\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 !! Spatial domain   !!\n\
 !! (rarely changed) !!\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 zp = 1\n\
 jtwist = -1\n\
\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 !! Species          !!\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 nspec = 1\n\
 tite = 1.0\n\
 iphi00 = 2\n\
\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 !! Fields           !!\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 fphi =   1.0\n\
 fapar =  0.0\n\
 faperp = 0.0\n\
 beta = 0.0\n\
\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 !! Nonlinearity     !!\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 nonlinear_mode='off'\n\
 cfl = 0.1\n\
\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 !! Geometry         !!\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 igeo       = 0\n\
 geofile    = \"eik.out\"\n\
 slab       = \"off\"\n\
 const_curv = \"off\"\n\
\n\
 rhoc = 0.54\n\
 eps = 0.18 \n\
 epsl = 2.0\n\
 \n\
 shat = 0.8\n\
 qinp = 1.4\n\
 shift = 0.0\n\
\n\
 akappa = 1.0\n\
 akappri = 0.0\n\
 tri = 0.0\n\
 tripri = 0.0\n\
\n\
 Rmaj = 1.0\n\
\n\
 beta_prime_input = 0.0\n\
 s_hat_input = 0.8\n\
\n\
 drhodpsi = 1.0\n\
 kxfac = 1.0\n\
\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 !! Rosenbluth-Hinton !\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 source_option = \"phiext+full\" !! RH\n\
 source_option = \"default\"\n\
 phi_ext = 0.\n\
! t0 = -10.0\n\
\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 !! Hyper-dissipation !\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 hyper = \"off\"\n\
 nu_hyper = 1.0\n\
 p_hyper = 2\n\
 d_hyper = 0.1 \n\
\n\
 hypercollisions = .false.\n\
 nu_hyper_l = 1\n\
 nu_hyper_m = 1\n\
 p_hyper_l = 6\n\
 p_hyper_m = 6\n\
\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 !! Initial conditions!\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 init_amp = 1.0e-5\n\
 init = \"density\"\n\
\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 !! Diagnostics      !!\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 write_omega = \"off\"\n\
 write_phi = \"off\"\n\
 write_h_spectrum = \"off\"\n\
 write_l_spectrum = \"off\"\n\
 write_lh_spectrum = \"off\"\n\
 hermite_spectrum_avg_cutoff = 20\n\
 write_moms = \"off\"\n\
 write_fluxes = \"off\"\n\
 write_spec_v_time = \"off\"\n\
\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 !! Rarely used      !!\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 zero_order_nonlin_flr_only = .false.\n\
 no_nonlin_cross_terms      = .false.\n\
 no_nonlin_dens_cross_term  = .false.\n\
\n\
 init_single = \"off\"\n\
 iky_single = 1\n\
 ikx_single = 0\n\
 kpar_init = 0.\n\
\n\
 snyder_electrons = \"off\"\n\
\n\
 forcing_init = \"off\"\n\
 forcing_type = \"Kz\"\n\
 forcing_amp = 1\n\
 forcing_index = 1\n\
\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 !! Available for use !\n\
 !!!!!!!!!!!!!!!!!!!!!!\n\
 ! netcdf_restart = .true.\n\
 ! append_old = .true.\n\
 ! nlpm = \"off\"\n\
 ! inlpm = 25\n\
 ! dnlpm = 1.0\n\
 ! dnlpm_dens = -0.4\n\
 ! dnlpm_tprp = 1.6\n\
 ! low_b_all = \"off\"\n\
 ! iflr = 0\n\
 ! avail_cpu_time = 1.e10\n\
 ! margin_cpu_time = 300.\n\
 ! iso_shear = \"off\"\n\
 ! scan_type = \"outputs\"\n\
 ! scan_number = 1\n\
 ! zero_restart_avg = \"off\"\n\
 ! no_zderiv_covering = \"off\"\n\
 ! no_zderiv= \"off\"\n\
 ! zderiv_loop = \"on\"\n\
 ! icovering = 1\n\
 ! no_landau_damping= \"off\"\n\
 ! turn_off_gradients_test = \"off\"\n\
 ! write_netcdf = .false.\n\
 ! restartfile = \"restart/linear.bin\"  \n\
 ! no_zonal_nlpm = .false.\n\
 ! dorland_qneut = \"off\"\n\
 ! stationary_ions = \"off\"\n\
 ! new_nlpm = \"on\"\n\
 ! hammett_nlpm_interference = \"off\"\n\
 ! higher_order_moments = \"off\"\n\
 ! nlpm_zonal_only = \"off\"\n\
 ! nlpm_vol_avg = \"off\"\n\
 ! nlpm_abs_sgn = \"off\"\n\
 ! nlpm_kxdep = \"off\"\n\
 ! nlpm_nlps = \"off\"\n\
 ! nlpm_cutoff_avg = \"off\"\n\
 ! nlpm_zonal_kx1_only = \"off\"\n\
 ! smagorinsky = \"off\"\n\
 ! dorland_nlpm = \"off\"\n\
 ! dorland_nlpm_phase = \"off\"\n\
 ! dorland_phase_complex = \"off\"\n\
 ! dorland_phase_ifac = 1\n\
 ! nlpm_option = \"constant\"\n\
 ! dnlpm_max = 1.0\n\
 ! tau_nlpm = 10.0   \n\
/\n\
\n\
&species_parameters_1\n\
 type  = 'ion'\n\
 z     = 1.0\n\
 mass  = 1.0\n\
 vnewk = 0.0\n\
 dens  = 1.0\n\
 temp  = 1.0\n\
 tprim = 6.9\n\
 fprim = 2.2\n\
 uprim = 0.0\n\
/\n\
&species_parameters_2\n\
 type  = 'ion'\n\
 z     = 1.0\n\
 mass  = 1.0\n\
 vnewk = 0.0\n\
 dens  = 1.0\n\
 temp  = 1.0\n\
 tprim = 6.9\n\
 fprim = 2.2\n\
 uprim = 0.0\n\
/\n\
&species_parameters_3\n\
 type  = 'ion'\n\
 z     = 1.0\n\
 mass  = 1.0\n\
 vnewk = 0.0\n\
 dens  = 1.0\n\
 temp  = 1.0\n\
 tprim = 6.9\n\
 fprim = 2.2\n\
 uprim = 0.0\n\
/\n\
\n\
&gx_nonlinear_terms_knobs\n\
 ! densfac = 1.\n\
 ! uparfac = 1.\n\
 ! tparfac = 1.\n\
 ! tprpfac = 1.\n\
 ! qparfac = 1.\n\
 ! qprpfac = 1.\n\
/\n\
\n\
";
