#include <hip/hip_complex.h>
#include <hipblas/hipblas.h>
#include <hip/hip_runtime.h>
#include <hipfft/hipfft.h>
#include <hipfft/hipfftXt.h>
#include <hipsolver/hipsolver.h>
#include <rccl/rccl.h>
#include <hiptensor/hiptensor.hpp>
#include <hiptensor/hiptensor_types.hpp>
#include <hipcub/hipcub.hpp>
#define  CUBLAS_OP_N  HIPBLAS_OP_N
#define  CUBLAS_STATUS_ALLOC_FAILED  HIPBLAS_STATUS_ALLOC_FAILED
#define  CUBLAS_STATUS_ARCH_MISMATCH  HIPBLAS_STATUS_ARCH_MISMATCH
#define  CUBLAS_STATUS_EXECUTION_FAILED  HIPBLAS_STATUS_EXECUTION_FAILED
#define  CUBLAS_STATUS_INTERNAL_ERROR  HIPBLAS_STATUS_INTERNAL_ERROR
#define  CUBLAS_STATUS_INVALID_VALUE  HIPBLAS_STATUS_INVALID_VALUE
#define  CUBLAS_STATUS_LICENSE_ERROR  HIPBLAS_STATUS_UNKNOWN
#define  CUBLAS_STATUS_MAPPING_ERROR  HIPBLAS_STATUS_MAPPING_ERROR
#define  CUBLAS_STATUS_NOT_INITIALIZED  HIPBLAS_STATUS_NOT_INITIALIZED
#define  CUBLAS_STATUS_NOT_SUPPORTED  HIPBLAS_STATUS_NOT_SUPPORTED
#define  CUBLAS_STATUS_SUCCESS  HIPBLAS_STATUS_SUCCESS
#define  CUFFT_C2C  HIPFFT_C2C
#define  CUFFT_C2R  HIPFFT_C2R
#define  CUFFT_CB_LD_COMPLEX  HIPFFT_CB_LD_COMPLEX
#define  CUFFT_CB_ST_COMPLEX  HIPFFT_CB_ST_COMPLEX
#define  CUFFT_FORWARD  HIPFFT_FORWARD
#define  CUFFT_INVERSE  HIPFFT_BACKWARD
#define  CUFFT_R2C  HIPFFT_R2C
#define  cuCabsf  hipCabsf
#define  cuCadd  hipCadd
#define  cuCaddf  hipCaddf
#define  cuCdiv  hipCdiv
#define  cuCdivf  hipCdivf
#define  cuCimagf  hipCimagf
#define  cuCmul  hipCmul
#define  cuCmulf  hipCmulf
#define  CUDA_R_32F  HIP_R_32F
#define  CUDA_R_64F  HIP_R_64F
#define  CUFFT_ALLOC_FAILED  HIPFFT_ALLOC_FAILED
#define  CUFFT_EXEC_FAILED  HIPFFT_EXEC_FAILED
#define  CUFFT_INCOMPLETE_PARAMETER_LIST  HIPFFT_INCOMPLETE_PARAMETER_LIST
#define  CUFFT_INTERNAL_ERROR  HIPFFT_INTERNAL_ERROR
#define  CUFFT_INVALID_DEVICE  HIPFFT_INVALID_DEVICE
#define  CUFFT_INVALID_PLAN  HIPFFT_INVALID_PLAN
#define  CUFFT_INVALID_SIZE  HIPFFT_INVALID_SIZE
#define  CUFFT_INVALID_TYPE  HIPFFT_INVALID_TYPE
#define  CUFFT_INVALID_VALUE  HIPFFT_INVALID_VALUE
#define  CUFFT_NOT_IMPLEMENTED  HIPFFT_NOT_IMPLEMENTED
#define  CUFFT_NOT_SUPPORTED  HIPFFT_NOT_SUPPORTED
#define  CUFFT_NO_WORKSPACE  HIPFFT_NO_WORKSPACE
#define  CUFFT_PARSE_ERROR  HIPFFT_PARSE_ERROR
#define  CUFFT_SETUP_FAILED  HIPFFT_SETUP_FAILED
#define  CUFFT_SUCCESS  HIPFFT_SUCCESS
#define  CUFFT_UNALIGNED_DATA  HIPFFT_UNALIGNED_DATA
#define  CURAND_STATUS_ALLOCATION_FAILED  HIPRAND_STATUS_ALLOCATION_FAILED
#define  CURAND_STATUS_ARCH_MISMATCH  HIPRAND_STATUS_ARCH_MISMATCH
#define  CURAND_STATUS_DOUBLE_PRECISION_REQUIRED  HIPRAND_STATUS_DOUBLE_PRECISION_REQUIRED
#define  CURAND_STATUS_INITIALIZATION_FAILED  HIPRAND_STATUS_INITIALIZATION_FAILED
#define  CURAND_STATUS_INTERNAL_ERROR  HIPRAND_STATUS_INTERNAL_ERROR
#define  CURAND_STATUS_LAUNCH_FAILURE  HIPRAND_STATUS_LAUNCH_FAILURE
#define  CURAND_STATUS_LENGTH_NOT_MULTIPLE  HIPRAND_STATUS_LENGTH_NOT_MULTIPLE
#define  CURAND_STATUS_NOT_INITIALIZED  HIPRAND_STATUS_NOT_INITIALIZED
#define  CURAND_STATUS_OUT_OF_RANGE  HIPRAND_STATUS_OUT_OF_RANGE
#define  CURAND_STATUS_PREEXISTING_FAILURE  HIPRAND_STATUS_PREEXISTING_FAILURE
#define  CURAND_STATUS_SUCCESS  HIPRAND_STATUS_SUCCESS
#define  CURAND_STATUS_TYPE_ERROR  HIPRAND_STATUS_TYPE_ERROR
#define  CURAND_STATUS_VERSION_MISMATCH  HIPRAND_STATUS_VERSION_MISMATCH
#define  CUSOLVER_STATUS_ALLOC_FAILED  HIPSOLVER_STATUS_ALLOC_FAILED
#define  CUSOLVER_STATUS_ARCH_MISMATCH  HIPSOLVER_STATUS_ARCH_MISMATCH
#define  CUSOLVER_STATUS_EXECUTION_FAILED  HIPSOLVER_STATUS_EXECUTION_FAILED
#define  CUSOLVER_STATUS_INTERNAL_ERROR  HIPSOLVER_STATUS_INTERNAL_ERROR
#define  CUSOLVER_STATUS_INVALID_VALUE  HIPSOLVER_STATUS_INVALID_VALUE
#define  CUSOLVER_STATUS_MAPPING_ERROR  HIPSOLVER_STATUS_MAPPING_ERROR
#define  CUSOLVER_STATUS_MATRIX_TYPE_NOT_SUPPORTED  HIPSOLVER_STATUS_MATRIX_TYPE_NOT_SUPPORTED
#define  CUSOLVER_STATUS_NOT_INITIALIZED  HIPSOLVER_STATUS_NOT_INITIALIZED
#define  CUSOLVER_STATUS_NOT_SUPPORTED  HIPSOLVER_STATUS_NOT_SUPPORTED
#define  CUSOLVER_STATUS_SUCCESS  HIPSOLVER_STATUS_SUCCESS
#define  CUSOLVER_STATUS_ZERO_PIVOT  HIPSOLVER_STATUS_ZERO_PIVOT
#define  CUSPARSE_STATUS_ALLOC_FAILED  HIPSPARSE_STATUS_ALLOC_FAILED
#define  CUSPARSE_STATUS_ARCH_MISMATCH  HIPSPARSE_STATUS_ARCH_MISMATCH
#define  CUSPARSE_STATUS_EXECUTION_FAILED  HIPSPARSE_STATUS_EXECUTION_FAILED
#define  CUSPARSE_STATUS_INTERNAL_ERROR  HIPSPARSE_STATUS_INTERNAL_ERROR
#define  CUSPARSE_STATUS_INVALID_VALUE  HIPSPARSE_STATUS_INVALID_VALUE
#define  CUSPARSE_STATUS_MAPPING_ERROR  HIPSPARSE_STATUS_MAPPING_ERROR
#define  CUSPARSE_STATUS_MATRIX_TYPE_NOT_SUPPORTED  HIPSPARSE_STATUS_MATRIX_TYPE_NOT_SUPPORTED
#define  CUSPARSE_STATUS_NOT_INITIALIZED  HIPSPARSE_STATUS_NOT_INITIALIZED
#define  CUSPARSE_STATUS_SUCCESS  HIPSPARSE_STATUS_SUCCESS
#define  CUresult  hipError_t
#define  cuComplex  hipComplex
#define  cuComplexDoubleToFloat  hipComplexDoubleToFloat
#define  cuConjf  hipConjf
#define  cuCrealf  hipCrealf
#define  cuCsub  hipCsub
#define  cuCsubf  hipCsubf
#define  cuDoubleComplex  hipDoubleComplex
#define  cublasCreate  hipblasCreate
#define  cublasDestroy  hipblasDestroy
#define  cuGetErrorName  hipDrvGetErrorName
#define  cublasHandle_t  hipblasHandle_t
#define  cublasSetStream  hipblasSetStream
#define  cublasSgemmStridedBatched  hipblasSgemmStridedBatched
#define  cublasStatus_t  hipblasStatus_t
#define  cublasGetStatusName hipblasStatusToString
#define  cudaComputeModeProhibited  hipComputeModeProhibited
#define  cudaDataType_t  hipDataType
#define  cudaDevAttrClockRate  hipDeviceAttributeClockRate
#define  cudaDevAttrComputeCapabilityMajor  hipDeviceAttributeComputeCapabilityMajor
#define  cudaDevAttrComputeCapabilityMinor  hipDeviceAttributeComputeCapabilityMinor
#define  cudaDevAttrComputeMode  hipDeviceAttributeComputeMode
#define  cudaDevAttrIntegrated  hipDeviceAttributeIntegrated
#define  cudaDevAttrMultiProcessorCount  hipDeviceAttributeMultiprocessorCount
#define  cudaDeviceGetAttribute  hipDeviceGetAttribute
#define  cudaDeviceProp  hipDeviceProp_t
#define  cudaDeviceReset  hipDeviceReset
#define  cudaDeviceSynchronize  hipDeviceSynchronize
#define  cudaErrorInvalidValue  hipErrorInvalidValue
#define  cudaError_t  hipError_t
#define  cudaEventCreate  hipEventCreate
#define  cudaEventElapsedTime  hipEventElapsedTime
#define  cudaEventRecord  hipEventRecord
#define  cudaEventSynchronize  hipEventSynchronize
#define  cudaEvent_t  hipEvent_t
#define  cudaFree  hipFree
#define  cudaFuncAttributeMaxDynamicSharedMemorySize  hipFuncAttributeMaxDynamicSharedMemorySize
#define  cudaFuncSetAttribute  hipFuncSetAttribute
#define  cudaGetDevice  hipGetDevice
#define  cudaGetDeviceCount  hipGetDeviceCount
#define  cudaGetDeviceProperties  hipGetDeviceProperties
#define  cudaGetErrorName  hipGetErrorName
#define  cudaGetErrorString  hipGetErrorString
#define  cudaGetLastError  hipGetLastError
#define  cudaMalloc  hipMalloc
#define  cudaMallocHost  hipHostMalloc
#define  cudaMemGetInfo  hipMemGetInfo
#define  cudaMemcpy  hipMemcpy
#define  cudaMemcpyAsync  hipMemcpyAsync
#define  cudaMemcpyFromSymbol  hipMemcpyFromSymbol
#define  cudaMemcpyDeviceToDevice  hipMemcpyDeviceToDevice
#define  cudaMemcpyDeviceToHost  hipMemcpyDeviceToHost
#define  cudaMemcpyHostToDevice  hipMemcpyHostToDevice
#define  cudaMemcpyToSymbol  hipMemcpyToSymbol
#define  cudaMemset  hipMemset
#define  cudaSetDevice  hipSetDevice
#define  cudaStreamCreate  hipStreamCreate
#define  cudaStreamCreateWithFlags  hipStreamCreateWithFlags
#define  cudaStreamDestroy  hipStreamDestroy
#define  cudaStreamNonBlocking  hipStreamNonBlocking
#define  cudaStreamSynchronize  hipStreamSynchronize
#define  cudaStreamWaitEvent  hipStreamWaitEvent
#define  cudaStream_t  hipStream_t
#define  cudaSuccess  hipSuccess
#define  cudaUUID_t  hipUUID
#define  cufftCallbackLoadC  hipfftCallbackLoadC
#define  cufftCallbackStoreC  hipfftCallbackStoreC
#define  cufftComplex  hipfftComplex
#define  cufftCreate  hipfftCreate
#define  cufftDestroy  hipfftDestroy
#define  cufftExecC2C  hipfftExecC2C
#define  cufftExecC2R  hipfftExecC2R
#define  cufftExecR2C  hipfftExecR2C
#define  cufftHandle  hipfftHandle
#define  cufftMakePlanMany  hipfftMakePlanMany
#define  cufftPlan1d  hipfftPlan1d
#define  cufftXtClearCallback  hipfftXtClearCallback
#define  cufftXtSetCallback  hipfftXtSetCallback
#define  cufftSetStream hipfftSetStream
#define  cusolverDnCreate  hipsolverDnCreate
#define  cusolverDnDgetrf  hipsolverDnDgetrf
#define  cusolverDnDgetrf_bufferSize  hipsolverDnDgetrf_bufferSize
#define  cusolverDnDgetrs  hipsolverDnDgetrs
#define  cufftResult  hipfftResult
#define  curandStatus_t  hiprandStatus_t
#define  cusolverDnHandle_t  hipsolverHandle_t
#define  cusolverStatus_t  hipsolverStatus_t
#define  cusparseStatus_t  hipsparseStatus_t
#define  cusolverDnSetStream  hipsolverSetStream
#define  cusolverDnZgetrf  hipsolverDnZgetrf
#define  cusolverDnZgetrf_bufferSize  hipsolverDnZgetrf_bufferSize
#define  cusolverDnZgetrs  hipsolverDnZgetrs
#define  make_cuComplex  make_hipComplex
#define  make_cuDoubleComplex  make_hipDoubleComplex
#define  GPU_SYMBOL(X) HIP_SYMBOL(X)
#define  cutensorCreate hiptensorCreate
#define  cutensorInitTensorDescriptor hiptensorInitTensorDescriptor
#define  cutensorCreatePlanPreference hiptensorCreatePlanPreference
#define  CUTENSOR_ALGO_DEFAULT HIPTENSOR_ALGO_DEFAULT
#define  CUTENSOR_JIT_MODE_DEFAULT HIPTENSOR_JIT_MODE_DEFAULT 
#define  cutensorDestroyTensorDescriptor hiptensorDestroyTensorDescriptor
#define  cutensorDestroyPlanPreference hiptensorDestroyPlanPreference
#define  cutensorDestroy hiptensorDestroy
#define  cutensorCreateReduction hiptensorCreateReduction
#define  CUTENSOR_OP_IDENTITY HIPTENSOR_OP_IDENTITY
#define  CUTENSOR_OP_ADD HIPTENSOR_OP_ADD
#define  CUTENSOR_OP_MAX HIPTENSOR_OP_MAX
#define  cutensorEstimateWorkspaceSize hiptensorEstimateWorkspaceSize
#define  cutensorCreatePlan hiptensorCreatePlan
#define  cutensorReduction hiptensorReduction
#define  CUTENSOR_WORKSPACE_DEFAULT HIPTENSOR_WORKSPACE_DEFAULT
#define  CUTENSOR_STATUS_SUCCESS HIPTENSOR_STATUS_SUCCESS
#define  cutensorGetErrorString hiptensorGetErrorString
#define  cutensorComputeType_t hiptensorComputeType_t
#define  CUTENSOR_COMPUTE_32F HIPTENSOR_COMPUTE_32F
#define  CUTENSOR_COMPUTE_64F HIPTENSOR_COMPUTE_64F
#define  CUDA_R_32F HIP_R_32F
#define  CUDA_R_64F HIP_R_64F
#define  cutensorHandle_t hiptensorHandle_t
#define  cutensorOperator_t hiptensorOperator_t
#define  cutensorPlanPreference_t hiptensorPlanPreference_t
#define  cutensorPlan_t hiptensorPlan_t
#define  cutensorTensorDescriptor_t hiptensorTensorDescriptor_t
#define  cutensorOperationDescriptor_t hiptensorOperationDescriptor_t
#define  cutensorContractionFind_t hiptensorContractionFind_t
#define  cutensorContractionDescriptor_t hiptensorContractionDescriptor_t
#define  cutensorContractionPlan_t hiptensorContractionPlan_t
#define  cutensorReductionGetWorkspaceSize hiptensorReductionGetWorkspaceSize 
#define  cub hipcub
